### ISSUE TITLE
The version

### ISSUE THREAD

**Issue by Fabio1018** [IamTheDefender/BedWars1058-ItemRotation#2]
Hello, when I first launched item rotation it doesn't worked. I found the solution but the thing is the latest version of your plugin is 1.19.3 (in the introduction page) and 1.19.2 in installation page) My server is on 1.19.4... Can you update to that version? Thank you!

**Comment by IamTheDefender** [comment]
Hello, can you provide me with your server logs and are you in the support
discord server? Because I have uploaded a dev build in the support server
for the versions

**Comment by IamTheDefender** [comment]
Closing due to no reply from the OP
